apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIKFIfl9g9kGEwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA4MTYxMDQ0NTNaFw0zNjA4MTMxMDQ5NTNaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC+zQCg0CJNZD1+kflonbQlQVye0aN5vmMkRhB3ITC0oY+Gd6MgU6xX+wtO
      oO8ZfW+0/MDV+Dw1DsC+1S+plfEqwEI49Q5KWstvbODrfUWJ8q+cPxx1Qr9kxWqs
      EbdoxlfDO+aVmraQFSRIACDO63YnoCAKue8DIPsZfA6B6yf8NaxWYz1gnhJ9SyJe
      jj0Ou2CMf2/xEDQClELzBMZ440Y86YAARpTRXhMtJYwpEnQ2TGgU/UP4xVHSOWOL
      GEg6zGhBgkAE8C6DeeVCGa3HXQ2Yl6k8LoMbl6RNdp6CjlkanecCo9VmHKKUGbeL
      EqGozhMBBMOvpSxsbjQty6JYhLFlAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQcLKU3fJqWMsMkMSMzYn7BuRjXtDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCSiecyFjqb
      eoNv8ZuJkdWyRdbMCigxIQHC5xAd+yWB7nj2NAosTLsaDKRzoSWYx935m1TeHJdn
      FEi/7IalLRsV4PmHug+ZQmyfEqnZNqZhZDgjwWQb90epKxNDhKrkNHB9xEXiO1qZ
      gFLbNgy3T8pWYND6CKf9RlSeQzeUINLoMmNwE40CHIGp9TQvL4IaVFLMQ3yvuQ0B
      uP/wdNtLxNbCQpKn4GawzabgZ0A1CkK/WIlnqgRMh4ejwy/wiv2/29+EizbJ8ia8
      x0hAsoTs1D1abTeH5E0rehLsHKxV3hFJYq8uuF890nd2qzWNxpdC8Xjyv30op9UO
      mQpBxWE4VxOQ
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-08-20T18:56:51Z"
    name: kube-root-ca.crt
    namespace: mediawiki
    resourceVersion: "532015"
    uid: ab97d78a-2e82-4187-a590-9667ce142539
- apiVersion: v1
  data:
    LocalSettings.php: "<?php\n# This file was automatically generated by the MediaWiki
      1.46.0\n# installer. If you make manual changes, please keep track in case you\n#
      need to recreate them later.\n#\n# See includes/MainConfigSchema.php for all
      configurable settings\n# and their default values, but don't forget to make
      changes in _this_\n# file, not there.\n#\n# Further documentation for configuration
      settings may be found at:\n# https://www.mediawiki.org/wiki/Manual:Configuration_settings\n\n#
      Protect against web entry\nif ( !defined( 'MEDIAWIKI' ) ) {\n\texit;\n}\n\n\n\n\n##
      Uncomment this to disable output compression\n# $wgDisableOutputCompression
      = true;\n\n$wgSitename = \"DevOps1988\";\n\n## The URL base path to the directory
      containing the wiki;\n## defaults for all runtime URL paths are based off of
      this.\n## For more information on customizing the URLs\n## (like /w/index.php/Page_title
      to /wiki/Page_title) please see:\n## https://www.mediawiki.org/wiki/Manual:Short_URL\n$wgScriptPath
      = \"\";\n\n## The protocol and server name to use in fully-qualified URLs\n$wgServer
      = \"https://wiki.devops1988.website\";\n\n## The URL path to static resources
      (images, scripts, etc.)\n$wgResourceBasePath = $wgScriptPath;\n\n## The URL
      paths to the logo.  Make sure you change this from the default,\n## or else
      you'll overwrite your logo when you upgrade!\n$wgLogos = [\n\t'1x' => \"$wgResourceBasePath/resources/assets/change-your-logo.svg\",\n\t'icon'
      => \"$wgResourceBasePath/resources/assets/change-your-logo-icon.svg\",\n];\n\n##
      UPO means: this is also a user preference option\n\n$wgEnableEmail = true;\n$wgEnableUserEmail
      = true; # UPO\n\n$wgEmergencyContact = \"\";\n$wgPasswordSender = \"\";\n\n$wgEnotifUserTalk
      = false; # UPO\n$wgEnotifWatchlist = false; # UPO\n$wgEmailAuthentication =
      true;\n\n## Database settings\n$wgDBtype = \"postgres\";\n$wgDBserver = \"mediawiki-postgres.mediawiki.svc.cluster.local\";\n$wgDBname
      = \"mediawiki\";\n$wgDBuser = \"mediawiki\";\n$wgDBpassword = \"c79836d3d3970cc2df21a9bf31350d3f27875fd8129cb596524df3af10ac219d\";\n\n#
      Postgres specific settings\n$wgDBport = \"5432\";\n$wgDBssl = false;\n$wgDBmwschema
      = \"mediawiki\";\n\n# Shared database table\n# This has no effect unless $wgSharedDB
      is also set.\n$wgSharedTables[] = \"actor\";\n\n## Shared memory settings\n$wgMainCacheType
      = CACHE_ACCEL;\n$wgMemCachedServers = [];\n\n## To enable image uploads, make
      sure the 'images' directory\n## is writable, then set this to true:\n$wgEnableUploads
      = false;\n$wgUseImageMagick = true;\n$wgImageMagickConvertCommand = \"/usr/bin/convert\";\n\n#
      InstantCommons allows wiki to use images from https://commons.wikimedia.org\n$wgUseInstantCommons
      = false;\n\n# Periodically send a pingback to https://www.mediawiki.org/ with
      basic data\n# about this MediaWiki instance. The Wikimedia Foundation shares
      this data\n# with MediaWiki developers to help guide future development efforts.\n$wgPingback
      = false;\n\n# Site language code, should be one of the list in ./includes/Languages/Data/Names.php\n$wgLanguageCode
      = \"ru\";\n\n# Time zone\n$wgLocaltimezone = \"UTC\";\n\n## Set $wgCacheDirectory
      to a writable directory on the web server\n## to make your wiki go slightly
      faster. The directory should not\n## be publicly accessible from the web.\n#$wgCacheDirectory
      = \"$IP/cache\";\n\n$wgSecretKey = \"1ae179174bd2656eb8df88435287400430b69e27ae82d07528b8626c6ba5391a\";\n\n#
      Changing this will log out all existing sessions.\n$wgAuthenticationTokenVersion
      = \"1\";\n\n# Site upgrade key. Must be set to a string (default provided) to
      turn on the\n# web installer while LocalSettings.php is in place\n$wgUpgradeKey
      = \"f7b1c07f3804f5a5\";\n\n## For attaching licensing metadata to pages, and
      displaying an\n## appropriate copyright notice / icon. GNU Free Documentation\n##
      License and Creative Commons licenses are supported so far.\n$wgRightsPage =
      \"\"; # Set to the title of a wiki page that describes your license/copyright\n$wgRightsUrl
      = \"\";\n$wgRightsText = \"\";\n$wgRightsIcon = \"\";\n\n# Path to the GNU diff3
      utility. Used for conflict resolution.\n$wgDiff3 = \"/usr/bin/diff3\";\n\n##
      Default skin: you can change the default skin. Use the internal symbolic\n##
      names, e.g. 'vector' or 'monobook':\n$wgDefaultSkin = \"vector-2022\";\n\n#
      Enabled skins.\n# The following skins were automatically enabled:\nwfLoadSkin(
      'MinervaNeue' );\nwfLoadSkin( 'MonoBook' );\nwfLoadSkin( 'Timeless' );\nwfLoadSkin(
      'Vector' );\n\n\n# End of automatically generated settings.\n# Add more configuration
      options below.\n\n# BEGIN ANSIBLE MANAGED HA SETTINGS\n$wgServer = \"https://wiki.devops1988.website\";\n$wgCanonicalServer
      = \"https://wiki.devops1988.website\";\n$wgScriptPath = \"\";\n$wgArticlePath
      = \"/$1\";\n$wgUsePathInfo = true;\n\n$wgForceHTTPS = true;\n$wgCookieSecure
      = true;\n$wgCookieSameSite = \"Lax\";\n\n$wgSessionCacheType = CACHE_DB;\n$wgCacheDirectory
      = \"/var/cache/mediawiki\";\n\n# Включим после настройки общего каталога images.\n$wgEnableUploads
      = false;\n# END ANSIBLE MANAGED HA SETTINGS\n"
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"LocalSettings.php":"\u003c?php\n# This file was automatically generated by the MediaWiki 1.46.0\n# installer. If you make manual changes, please keep track in case you\n# need to recreate them later.\n#\n# See includes/MainConfigSchema.php for all configurable settings\n# and their default values, but don't forget to make changes in _this_\n# file, not there.\n#\n# Further documentation for configuration settings may be found at:\n# https://www.mediawiki.org/wiki/Manual:Configuration_settings\n\n# Protect against web entry\nif ( !defined( 'MEDIAWIKI' ) ) {\n\texit;\n}\n\n\n\n\n## Uncomment this to disable output compression\n# $wgDisableOutputCompression = true;\n\n$wgSitename = \"DevOps1988\";\n\n## The URL base path to the directory containing the wiki;\n## defaults for all runtime URL paths are based off of this.\n## For more information on customizing the URLs\n## (like /w/index.php/Page_title to /wiki/Page_title) please see:\n## https://www.mediawiki.org/wiki/Manual:Short_URL\n$wgScriptPath = \"\";\n\n## The protocol and server name to use in fully-qualified URLs\n$wgServer = \"https://wiki.devops1988.website\";\n\n## The URL path to static resources (images, scripts, etc.)\n$wgResourceBasePath = $wgScriptPath;\n\n## The URL paths to the logo.  Make sure you change this from the default,\n## or else you'll overwrite your logo when you upgrade!\n$wgLogos = [\n\t'1x' =\u003e \"$wgResourceBasePath/resources/assets/change-your-logo.svg\",\n\t'icon' =\u003e \"$wgResourceBasePath/resources/assets/change-your-logo-icon.svg\",\n];\n\n## UPO means: this is also a user preference option\n\n$wgEnableEmail = true;\n$wgEnableUserEmail = true; # UPO\n\n$wgEmergencyContact = \"\";\n$wgPasswordSender = \"\";\n\n$wgEnotifUserTalk = false; # UPO\n$wgEnotifWatchlist = false; # UPO\n$wgEmailAuthentication = true;\n\n## Database settings\n$wgDBtype = \"postgres\";\n$wgDBserver = \"mediawiki-postgres.mediawiki.svc.cluster.local\";\n$wgDBname = \"mediawiki\";\n$wgDBuser = \"mediawiki\";\n$wgDBpassword = \"c79836d3d3970cc2df21a9bf31350d3f27875fd8129cb596524df3af10ac219d\";\n\n# Postgres specific settings\n$wgDBport = \"5432\";\n$wgDBssl = false;\n$wgDBmwschema = \"mediawiki\";\n\n# Shared database table\n# This has no effect unless $wgSharedDB is also set.\n$wgSharedTables[] = \"actor\";\n\n## Shared memory settings\n$wgMainCacheType = CACHE_ACCEL;\n$wgMemCachedServers = [];\n\n## To enable image uploads, make sure the 'images' directory\n## is writable, then set this to true:\n$wgEnableUploads = false;\n$wgUseImageMagick = true;\n$wgImageMagickConvertCommand = \"/usr/bin/convert\";\n\n# InstantCommons allows wiki to use images from https://commons.wikimedia.org\n$wgUseInstantCommons = false;\n\n# Periodically send a pingback to https://www.mediawiki.org/ with basic data\n# about this MediaWiki instance. The Wikimedia Foundation shares this data\n# with MediaWiki developers to help guide future development efforts.\n$wgPingback = false;\n\n# Site language code, should be one of the list in ./includes/Languages/Data/Names.php\n$wgLanguageCode = \"ru\";\n\n# Time zone\n$wgLocaltimezone = \"UTC\";\n\n## Set $wgCacheDirectory to a writable directory on the web server\n## to make your wiki go slightly faster. The directory should not\n## be publicly accessible from the web.\n#$wgCacheDirectory = \"$IP/cache\";\n\n$wgSecretKey = \"1ae179174bd2656eb8df88435287400430b69e27ae82d07528b8626c6ba5391a\";\n\n# Changing this will log out all existing sessions.\n$wgAuthenticationTokenVersion = \"1\";\n\n# Site upgrade key. Must be set to a string (default provided) to turn on the\n# web installer while LocalSettings.php is in place\n$wgUpgradeKey = \"f7b1c07f3804f5a5\";\n\n## For attaching licensing metadata to pages, and displaying an\n## appropriate copyright notice / icon. GNU Free Documentation\n## License and Creative Commons licenses are supported so far.\n$wgRightsPage = \"\"; # Set to the title of a wiki page that describes your license/copyright\n$wgRightsUrl = \"\";\n$wgRightsText = \"\";\n$wgRightsIcon = \"\";\n\n# Path to the GNU diff3 utility. Used for conflict resolution.\n$wgDiff3 = \"/usr/bin/diff3\";\n\n## Default skin: you can change the default skin. Use the internal symbolic\n## names, e.g. 'vector' or 'monobook':\n$wgDefaultSkin = \"vector-2022\";\n\n# Enabled skins.\n# The following skins were automatically enabled:\nwfLoadSkin( 'MinervaNeue' );\nwfLoadSkin( 'MonoBook' );\nwfLoadSkin( 'Timeless' );\nwfLoadSkin( 'Vector' );\n\n\n# End of automatically generated settings.\n# Add more configuration options below.\n\n# BEGIN ANSIBLE MANAGED HA SETTINGS\n$wgServer = \"https://wiki.devops1988.website\";\n$wgCanonicalServer = \"https://wiki.devops1988.website\";\n$wgScriptPath = \"\";\n$wgArticlePath = \"/$1\";\n$wgUsePathInfo = true;\n\n$wgForceHTTPS = true;\n$wgCookieSecure = true;\n$wgCookieSameSite = \"Lax\";\n\n$wgSessionCacheType = CACHE_DB;\n$wgCacheDirectory = \"/var/cache/mediawiki\";\n\n# Включим после настройки общего каталога images.\n$wgEnableUploads = false;\n# END ANSIBLE MANAGED HA SETTINGS\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"mediawiki-localsettings","namespace":"mediawiki"}}
    creationTimestamp: "2026-08-20T20:28:45Z"
    name: mediawiki-localsettings
    namespace: mediawiki
    resourceVersion: "2380227"
    uid: e67b7f5e-81e6-49b9-9b21-a4b00caad972
kind: List
metadata:
  resourceVersion: ""
