apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mediawiki","namespace":"mediawiki"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"mediawiki"},"type":"ClusterIP"}}
    creationTimestamp: "2026-08-20T20:26:33Z"
    name: mediawiki
    namespace: mediawiki
    resourceVersion: "600684"
    uid: 93724801-3929-453c-881b-e42f19b3dfba
  spec:
    clusterIP: 10.104.180.24
    clusterIPs:
    - 10.104.180.24
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31046
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: mediawiki
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mediawiki-postgres","namespace":"mediawiki"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"mediawiki-postgres"}}}
    creationTimestamp: "2026-08-20T19:05:34Z"
    name: mediawiki-postgres
    namespace: mediawiki
    resourceVersion: "532866"
    uid: 0c56a171-5770-41ce-a02c-a9900741bf39
  spec:
    clusterIP: 10.109.185.71
    clusterIPs:
    - 10.109.185.71
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: mediawiki-postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
